**What does pseudorandom mean?**

The numbers look random, but they are actually generated by a deterministic algorithm.

If you give the same seed, you’ll get the same sequence of “random” numbers every time.

**Why use NumPy’s random instead of Python’s random?**

Python’s random module → generates one number at a time.

NumPy’s random module → can generate whole arrays of random numbers at once (much faster and efficient for data science).

In [2]:
import numpy as np

In [3]:
samples = np.random.standard_normal(size=(4, 4))
samples

array([[-0.0579681 , -0.78735523,  1.80785966, -0.45984858],
       [-1.43995109, -0.84784322,  0.72652223, -0.21078677],
       [ 0.61128235, -1.19747869, -0.01904477,  0.41786181],
       [ 0.46744908, -1.39419319, -0.80341241, -0.07211917]])

In [9]:
samples = np.random.standard_normal((3,3))    
samples

array([[ 1.45590385, -0.01026776, -0.81857599],
       [ 0.83178264, -0.7843905 ,  2.01603839],
       [-0.03357561, -1.09198277, -0.21725727]])

Instead of relying on NumPy’s global random state, you can make your own generator object:

seed ensures reproducibility (same random numbers every time).

Each generator (rng) is independent of others.

Safer and more controlled than np.random.* functions.

In [11]:
rng = np.random.default_rng(seed=12345)   # create generator with seed
data = rng.standard_normal((2, 3))   
data

array([[-1.42382504,  1.26372846, -0.87066174],
       [-0.25917323, -0.07534331, -0.74088465]])

In [13]:
type(rng)
np.random._generator.Generator

numpy.random._generator.Generator

## Common RNG Methods

Some useful ones you’ll often use:

**rng.integers(low, high, size)** → random integers
**
rng.uniform(low, high, size)** → uniform distribution

**rng.standard_normal(size)** → normal distribution (mean=0, std=1)

**rng.normal(mean, std, size)** → normal with custom mean & std

**rng.binomial(n, p, size)** → binomial distribution

**rng.permutation(seq)** → return a permuted sequence

**rng.shuffle(seq)** → shuffle in place