In [1]:
import numpy as np

In [2]:
M = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])   # Shape: (3, 3)

row_add = np.array([10, 20, 30])  # Shape: (3,)

# Broadcast: (3,3) + (3,) → matches last dimension
result = M + row_add
print(result)

[[11 22 33]
 [14 25 36]
 [17 28 39]]
