In [1]:
import numpy as np

**NP.ARRAY()**

In [2]:
arr1 = np.array([2,4,6,8,10])
arr1

array([ 2,  4,  6,  8, 10])

**NP.ZEROS()**

In [8]:
arr2 = np.zeros((2,2))
arr2

array([[0., 0.],
       [0., 0.]])

**NP.ONES()**

In [11]:
arr3 = np.ones((5,5))
arr3

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

**NP.ARANGE()**

In [12]:
arr4 = np.arange(0, 10, 2) 
arr4

array([0, 2, 4, 6, 8])

**NP.LINSPACE**

np.linspace(start, stop, num) → returns evenly spaced numbers over a specified range.

start = 0 → starting value.

stop = 1 → ending value (inclusive).

num = 5 → how many numbers you want between start and stop.

In [ ]:
arr5 = np.linspace(0, 1, 5)  
arr5

array([0.  , 0.25, 0.5 , 0.75, 1.  ])