In [2]:
import numpy as np

**.reshape()**

Purpose: Change the shape (dimensions) of an array without changing its data.

Key Points:

Returns a new view of the array when possible (shares the same data in memory).

The total number of elements must stay the same.

You can use -1 for one dimension, and NumPy will figure it out.

In [3]:
arr1 = np.arange(6) 
reshaped_arr1 = arr1.reshape(2,3)
reshaped_arr1


arr2 = np.array([1,2,3,4,5,6,7,8,9,10])
reshaped_arr2 = arr2.reshape(2,5)
reshaped_arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

**.ravel()**

Purpose: Convert a multi-dimensional array into a 1D view (flatten it).

Key Points:

Returns a view of the original array (changes in one affect the other, if possible).

More memory-efficient than .flatten().

In [ ]:
arr3 = np.array([[1,2,3],[4,5,6]])
r = arr3.ravel()
print(r)  



r[0] = 99
print(arr3)    


[1 2 3 4 5 6]
[[99  2  3]
 [ 4  5  6]]


**flatten()**

Purpose: Convert a multi-dimensional array into a 1D copy.

Key Points:

Always returns a copy (changes in one do not affect the other).

Uses more memory than .ravel().

In [ ]:
arr4 = np.array([[1,2,3],[4,5,6]])
f = arr4.flatten()
print(f)      

f[0] = 99
print(arr4)  

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
