In [1]:
import numpy as np

### 1D Array Indexing & Slicing

**Indexing:**

Works like Python lists — indexes start from 0.

**Slicing:**

Format → arr[start:end:step]

start → index to begin (default 0)

end → index to stop (exclusive)

step → how many to skip (default 1)

In [10]:
arr1 = np.array([1,2,3,4,5,6,7,8,9])
arr1

print(f"First element: {arr1[0]}")
print(f"Last element: {arr1[-1]}")



print("Slicing: ")

print(arr1[0:5])
print(arr1[1:8:2])
print(arr1[:3])  
print(arr1[::2])

First element: 1
Last element: 9
Slicing: 
[1 2 3 4 5]
[2 4 6 8]
[1 2 3]
[1 3 5 7 9]


### 2D Array Indexing & Slicing

**Indexing:**

A 2D array is like a matrix → arr[row, column]

In [16]:
arr2 = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

arr2

arr2[1,2]
arr2[0,-1]

3

In [ ]:
print(arr2[0, :])    
print(arr2[:, 1])    
print(arr2[0:2, 1:3]) 

[1 2 3]
[2 5 8]
[[2 3]
 [5 6]]


### Multidimensional Slicing

Works the same way but for 3D arrays or more.

In [21]:
arr3d = np.arange(24).reshape(2, 3, 4)
arr3d

 

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [22]:
print(arr3d[0, 1, 2])    # Element in block 0, row 1, col 2
print(arr3d[:, 1, :])

6
[[ 4  5  6  7]
 [16 17 18 19]]


### Fancy Indexing

Fancy indexing = selecting elements using lists/arrays of indices.

In [25]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[[0, 3, 4]])     # [10 40 50]

arr2d = np.array([[1, 2],
                  [3, 4],
                  [5, 6]])
print(arr2d[[0, 2], [1, 0]])

#It takes row 0, column 1 → that’s the value 2

#It takes row 2, column 0 → that’s the value 5

[10 40 50]
[2 5]


### Boolean Indexing
Boolean indexing = filtering with conditions

In [32]:
arr3 = np.array([5,10,15,20,25,30,35,40,45,50])

mask = (arr3 > 15) & (arr3 < 35)
print(mask)

print(arr3[mask])


print(arr3[arr3 % 2==0])

[False False False  True  True  True False False False False]
[20 25 30]
[10 20 30 40 50]
