In [1]:
import numpy as np

In [2]:
arr1 = np.array([1, 2, 3], dtype=np.float64)
arr2 = np.array([1, 2, 3], dtype=np.int32)
print(arr1.dtype)
print(arr2.dtype)


float64
int32


### TYPECASTING: 
Converting or casting an array from one data type to another

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
print(float_arr)
float_arr.dtype


int32
[1. 2. 3. 4. 5.]


dtype('float64')

If I cast some floating-point
numbers to be of integer data type, the decimal part will be truncated:


In [4]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
print(arr)

arr.astype(np.int32)


[ 3.7 -1.2 -2.6  0.5 12.9 10.1]


array([ 3, -1, -2,  0, 12, 10])

If you have an array of strings representing numbers, you can use astype to convert
them to numeric form:

In [5]:
numeric_strings = np.array(["1.25", "-9.6", "42"], dtype=np.string_)
numeric_strings.astype(float)


array([ 1.25, -9.6 , 42.  ])

You can also use another array’s dtype attribute:


In [6]:
int_array = np.arange(10)
calibers = np.array([.22, .270, .357, .380, .44, .50], dtype=np.float64)
int_array.astype(calibers.dtype)

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])